version: '3.7'

services:
  server:
    image: maheshur/student-performance-server:latest
    container_name: myapp-node-server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - CLIENT_URL=http://43.205.210.137:3000
    networks:
      - app-network

  client:
    image: maheshur/student-performance-client:latest
    container_name: myapp-react-client
    depends_on:
      - server
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
